from printable_object import PrintableObject

"""
File Generated by Lisp2Python Translator
"""

class Issue(PrintableObject):

    """"
    A document that represnts a particular issue.
    """

    def __init__(self, **entries):

        """
        Constructs a new Issue object.

        name          -- name of issue
        type          -- type of issue
        sort_key      -- issue Sort Key
        synonyms      -- issue synonyms - list of symbols
        isa           -- List of symbols
        isa_depth     -- String for padding printing
        instances     -- List of issues
        polarity      -- Intrinsic position for this version of issue
        english       -- English version of issue name
        english_short -- short English phrase for issue
        pro_english   -- English phrase biased favorably
        con_english   -- pejorative English phrase
        french        -- French version of issue name
        french_short  -- short French phrase for issue
        pro_french    -- French phrase biased favorably
        con_french    -- pejorative French phrase
        number        -- sing or plur for generation
        groups        -- List of symbols
        pro_stances   -- List of stances supporting this issue
        con_stances   -- List of stances opposing this issue
        norm          -- Normative stance on this issue
        opposite      -- issue opposite of current issue
        notes         -- List of remarks

        return        -- returns nothing
        """
        self.name = None
        self.type = None
        self.sort_key = None
        self.synonyms = []
        self.isa = []
        self.isa_depth = None
        self.instances = []
        self.polarity = None
        self.english = None
        self.english_short = None
        self.pro_english = None
        self.con_english = None
        self.french = None
        self.french_short = None
        self.pro_french = None
        self.con_french = None
        self.number = None
        self.groups = []
        self.pro_stances = []
        self.con_stances = []
        self.norm = None
        self.opposite = None
        self.notes = []
        self.__dict__.update(entries)
