from printable_object import PrintableObject

"""
File Generated by Lisp2Python Translator
"""

class Bill(PrintableObject):

    """
    The Bill class represents bills that Congress is considering. Congressmen
    and Congresswomen will vote for these bills either for or against them.
    """

    def __init__(self, **entries):

        """
        Constructs a new Bill object.

        name            -- name of bill
        english         -- English version of bill name
        french          -- French version of bill name
        bnumber         -- Bill number
        sort_key        -- Bill Sort Key
        synonyms        -- Bill synonyms - list of symbols
        date_of_vote    -- Bill Vote date
        vote_tally      -- Vote tally list
        pres_pos        -- President's position FOR or AGN
        test_bill       -- Flag for test bills
        session         -- Session of Congress
        isa             -- List of symbols
        instances       -- List of bills
        majority_factor -- Number used for calculating votes required for passage
        issues          -- List of symbols
        importance      -- Intrinsic importance of bill
        stance_for      -- What voting for this bill implies
        stance_agn      -- What voting against this bill implies
        i_stance_for    -- What voting for this bill implies inferred from remarks
        i_stance_agn    -- What voting against this bill implies inferred from remarks
        notes           -- List of remarks

        return -- returns nothing
        """
        self.name = None
        self.english = None
        self.french = None
        self.bnumber = None
        self.sort_key = None
        self.synonyms = []
        self.date_of_vote = None
        self.vote_tally = []
        self.pres_pos = None
        self.test_bill = None
        self.session = None
        self.isa = []
        self.instances = []
        self.majority_factor = None
        self.issues = []
        self.importance = None
        self.stance_for = []
        self.stance_agn = []
        self.i_stance_for = []
        self.i_stance_agn = []
        self.notes = []
        self.__dict__.update(entries)

