from printable_object import PrintableObject

"""
File Generated by Lisp2Python Translator
"""

class DecisionDataDependency(PrintableObject):

    """"
    This class keeps tracks of which data the decision is dependent upon.
    """

    def __init__(self, updates, old_updates, decisions, old_decisions,
                 changed_strategy, changed_result):

        """
        Constructs a new DecisionDataDependency object.

        updates           -- slot+item pairs that have been changed, e.g.#{Selector ISSUE NORM} . #{Issue 634 B-1 Bomber}
        old_updates       -- slot+item pairs that have been processed
        decisions         -- decisions that might be affected by updates
        old_decisions     -- old decisions ?
        changed_strategy  -- pairs old/new decisions that have same result, but new strat
        changed_result    -- old/new pairs that have new result

        return            -- returns nothing
        """
        self.updates = updates
        self.old_updates = old_updates
        self.decisions = decisions
        self.old_decisions = old_decisions
        self.changed_strategy = changed_strategy
        self.changed_result = changed_result


