from printable_object import PrintableObject
import operator

"""
File Generated by Lisp2Python Translator
"""

class Decision(PrintableObject):

    """"
    An object for storing decisions on a bill.
    """

    def __init__(self, **entries):

        """
        Constructs a new Decision object.

        isa_depth           -- ?
        sort_key            -- ?
        bill                -- the bill the decision is being made on
        member              -- the member making the decision.
        for_stances         -- list of stances in favor
        agn_stances         -- list of stances opposed
        neg_for_stances     -- list of flip stances in favor
        neg_agn_stances     -- list of flip stances opposed
        con_rel_for_stances -- list of stances in favor by opposition
        con_rel_agn_stances -- list of stances opposed by opposition
        no_update           -- T until update-decision-metrics done
        number_for          -- number of reasons for
        number_agn          -- number of reasons agn
        group_for           -- list of groups in support
        group_agn           -- list of groups opposed
        for_norms           -- norms associated with for stances
        agn_norms           -- norms associated with agn stances
        for_bnorms          -- norms associated with bill's for stances
        agn_bnorms          -- norms associated with bill's agn stances
        split_group         -- list of groups on both sides
        split_record        -- t/nil if voting record is split
        split_credo         -- t/nil if own credo is split
        MI_stance           -- for/agn/nil -- >important? for agn
        MI_group            -- for/agn/nil
        MI_credo            -- for/agn/nil
        MI_record           -- for/agn/nil
        MI_norm             -- for/agn/nil
        strategy            -- decision strategy used to arrive at result
        result              -- for/agn -- position arrived at
        reason              -- support for position
        downside            -- negative aspects of decision
        downside_record     -- voting record stances supporting downside
        deeper_analysis     -- set by deeper-analysis strategy
        real_vote           -- actual vote for test bills
        score               -- accuracy of predicted vote

        return              -- returns nothing
        """
        self.isa_depth = None
        self.sort_key = None
        self.bill = []
        self.member = []
        self.for_stances = []
        self.agn_stances = []
        self.neg_for_stances = []
        self.neg_agn_stances = []
        self.con_rel_for_stances = []
        self.con_rel_agn_stances = []
        self.no_update = None
        self.number_for = None
        self.number_agn = None
        self.group_for = []
        self.group_agn = []
        self.for_norms = []
        self.agn_norms = []
        self.for_bnorms = []
        self.agn_bnorms = []
        self.split_group = []
        self.split_record = None
        self.split_credo = None
        self.MI_stance = None
        self.MI_group = None
        self.MI_credo = None
        self.MI_record = None
        self.MI_norm = None
        self.strategy = None
        self.result = None
        self.reason = None
        self.downside = None
        self.downside_record = []
        self.deeper_analysis = None
        self.real_vote = None
        self.score = None
        self.__dict__.update(entries)

