from printable_object import PrintableObject

"""
File Generated by Lisp2Python Translator
"""

class Group(PrintableObject):

    """"
    A class that represents a particular group.
    """

    def __init__(self, name, notes, gender, issues, stances, credo, english,
                 english_short, pro_english, con_english, french, french_short,
                 pro_french, con_french, number, synonyms, pro_stances,
                 con_stances, norm, instances):

        """
        Constructs a new Group object.

        name              -- name of group
        notes             -- list of remarks
        gender            -- male or female
        issues            -- list of issues of importance to this group
        stances           -- list of stances
        credo             -- list of stances personal to this group
        english           -- English version of group name
        english_short     -- short English phrase for group
        pro_english       -- English phrase biased favorably
        con_english       -- pejorative English phrase
        french            -- French version of group name
        french_short      -- short French phrase for group
        pro_french        -- French phrase biased favorably
        con_french        -- pejorative French phrase
        number            -- sing or plur for generation
        synonyms          -- List of symbols
        pro_stances       -- List of stances supporting this group
        con_stances       -- List of stances opposing this group
        norm              -- Normative relation to this group
        instances         -- List of groups

        return            -- returns nothing
        """
        self.name = name
        self.notes = notes
        self.gender = gender
        self.issues = issues
        self.stances = stances
        self.credo = credo
        self.english = english
        self.english_short = english_short
        self.pro_english = pro_english
        self.con_english = con_english
        self.french = french
        self.french_short = french_short
        self.pro_french = pro_french
        self.con_french = con_french
        self.number = number
        self.synonyms = synonyms
        self.pro_stances = pro_stances
        self.con_stances = con_stances
        self.norm = norm
        self.instances = instances


