from printable_object import PrintableObject

"""
File Generated by Lisp2Python Translator
"""

class Issue(PrintableObject):

    """"
    A document that represnts a particular issue.
    """

    def __init__(self, name, type, sort_key, synonyms, isa, isa_depth, instances,
                 polarity, english, english_short, pro_english, con_english,
                 french, french_short, pro_french, con_french, number, groups,
                 pro_stances, con_stances, norm, opposite, notes):

        """
        Constructs a new Issue object.

        name          -- name of issue
        type          -- type of issue
        sort_key      -- issue Sort Key
        synonyms      -- issue synonyms - list of symbols
        isa           -- List of symbols
        isa_depth     -- String for padding printing
        instances     -- List of issues
        polarity      -- Intrinsic position for this version of issue
        english       -- English version of issue name
        english_short -- short English phrase for issue
        pro_english   -- English phrase biased favorably
        con_english   -- pejorative English phrase
        french        -- French version of issue name
        french_short  -- short French phrase for issue
        pro_french    -- French phrase biased favorably
        con_french    -- pejorative French phrase
        number        -- sing or plur for generation
        groups        -- List of symbols
        pro_stances   -- List of stances supporting this issue
        con_stances   -- List of stances opposing this issue
        norm          -- Normative stance on this issue
        opposite      -- issue opposite of current issue
        notes         -- List of remarks

        return        -- returns nothing
        """
        self.name = name
        self.type = type
        self.sort_key = sort_key
        self.synonyms = synonyms
        self.isa = isa
        self.isa_depth = isa_depth
        self.instances = instances
        self.polarity = polarity
        self.english = english
        self.english_short = english_short
        self.pro_english = pro_english
        self.con_english = con_english
        self.french = french
        self.french_short = french_short
        self.pro_french = pro_french
        self.con_french = con_french
        self.number = number
        self.groups = groups
        self.pro_stances = pro_stances
        self.con_stances = con_stances
        self.norm = norm
        self.opposite = opposite
        self.notes = notes


