from printable_object import PrintableObject

"""
File Generated by Lisp2Python Translator
"""

class Relation(PrintableObject):

    """"
    A class that represents a particular relationship.
    """

    def __init__(self, **entries):

        """
        Constructs a new Relation object.

        source            -- particular instance of member, bill, issue, group, district
        source_db         -- db of source" 
        source_structure  -- ?" 
        group             -- relation group" 
        group_structure   -- ?" 
        importance        -- relation importance A, B, C, D" 
        side              -- relation side pro or con" 

        return            -- returns nothing
        """
        self.source = None
        self.source_db = None
        self.source_structure = None
        self.group = None
        self.group_structure = None
        self.importance = None
        self.side = None
        self.__dict__.update(entries)

