from printable_object import PrintableObject

"""
File Generated by Lisp2Python Translator
"""

class Relation(PrintableObject):

    """"
    A class that represents a particular relationship.
    """

    def __init__(self, source, source_db, source_structure, group,
                 group_structure, importance, side):

        """
        Constructs a new Relation object.

        source            -- particular instance of member, bill, issue, group, district
        source_db         -- db of source" 
        source_structure  -- ?" 
        group             -- relation group" 
        group_structure   -- ?" 
        importance        -- relation importance A, B, C, D" 
        side              -- relation side pro or con" 

        return            -- returns nothing
        """
        self.source = source
        self.source_db = source_db
        self.source_structure = source_structure
        self.group = group
        self.group_structure = group_structure
        self.importance = importance
        self.side = side


