from printable_object import PrintableObject

"""
File Generated by Lisp2Python Translator
"""

class Stance(PrintableObject):

    """"
    A class that represents a particular stance.
    """

    def __init__(self, source, source_db, source_structure, relation, issue,
                 issue_structure, importance, side, sort_key, siblings):

        """
        Constructs a new Stance object.

        source            -- particular instance of member, bill, issue, group
        source_db         -- db of source" 
        source_structure  -- ?" 
        relation          -- ?" 
        issue             -- stance issue" 
        issue_structure   -- ?" 
        importance        -- stance importance A, B, C, D" 
        side              -- stance side pro or con" 
        sort_key          -- ?" 
        siblings          -- related stances must be stance-alikev?

        return            -- returns nothing
        """
        self.source = source
        self.source_db = source_db
        self.source_structure = source_structure
        self.relation = relation
        self.issue = issue
        self.issue_structure = issue_structure
        self.importance = importance
        self.side = side
        self.sort_key = sort_key
        self.siblings = siblings


