from printable_object import PrintableObject

"""
File Generated by Lisp2Python Translator
"""

class Strategy(PrintableObject):

    """"
    Add documentation here.
    """

    def __init__(self, name, sort_key, keywords, synonyms, isa, isa_depth,
                 instances, polarity, quote, notes, rank, test, test_code,
                 preamble, protocol, example, no_second_try):

        """
        Constructs a new Strategy object.

        name          -- string
        sort_key      -- string
        keywords      -- list of symbols
        synonyms      -- list of symbols
        isa           -- list of symbols
        isa_depth     -- string for padding printing.
        instances     -- list of strategies
        polarity      -- intrinsic position for this version of the strategy
        quote         -- real quotation
        notes         -- list of remarks
        rank          -- selection order for this strategy
        test          -- predicate for testing applicability of this strategy [text]
        test_code     -- predicate code
        preamble      -- preamble English generation procedure
        protocol      -- procedure for generating transcript comments
        example       -- code to execute to test this strategy
        no_second_try -- flag -- don't execute this strategy at deep analysis

        return        -- returns nothing
        """
        self.name = name
        self.sort_key = sort_key
        self.keywords = keywords
        self.synonyms = synonyms
        self.isa = isa
        self.isa_depth = isa_depth
        self.instances = instances
        self.polarity = polarity
        self.quote = quote
        self.notes = notes
        self.rank = rank
        self.test = test
        self.test_code = test_code
        self.preamble = preamble
        self.protocol = protocol
        self.example = example
        self.no_second_try = no_second_try


